### ISSUE TITLE
README needed

### ISSUE THREAD

**Issue by gabrielmongefranco** [sobradob/shinyapp#1]
Hello - thank you for putting together this great visualization library for location data. I would like to link to your project from the University of Michigan's Mobile Technology Core github. I am wondering if you could add a README.md file to your project explaining what it does and how to use it? That would help mobile data researchers get started.

Thank you!

Gabriel Mongefranco
Mobile Data Architect
University of Michigan

**Comment by sobradob** [comment]
Thanks for getting in touch @gabrielmongefranco. I had no idea this was still running. Have added a readme with detail!
